<?php

namespace Database\Seeders;

use App\Models\RequestType;
use Illuminate\Database\Seeder;

class RequestTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            [
                'name' => 'Student Conference Grant',
                'slug' => 'student-conference',
                'description' => 'Financial support for students attending academic conferences',
                'requires_vot' => true,
                'field_schema' => [
                    [
                        'name' => 'conference_name',
                        'label' => 'Conference Name',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'e.g., International Conference on Computer Science',
                    ],
                    [
                        'name' => 'conference_location',
                        'label' => 'Conference Location',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'e.g., Kuala Lumpur, Malaysia',
                    ],
                    [
                        'name' => 'presentation_type',
                        'label' => 'Presentation Type',
                        'type' => 'select',
                        'required' => true,
                        'options' => ['Oral Presentation', 'Poster Presentation', 'Workshop'],
                    ],
                    [
                        'name' => 'paper_title',
                        'label' => 'Paper/Project Title',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Title of your research paper or project',
                    ],
                    [
                        'name' => 'travel_dates',
                        'label' => 'Travel Dates',
                        'type' => 'date_range',
                        'required' => true,
                        'fields' => ['start_date', 'end_date'],
                    ],
                    [
                        'name' => 'justification',
                        'label' => 'Justification for Attendance',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 4,
                        'placeholder' => 'Explain how this conference benefits your academic/professional development',
                    ],
                ],
            ],
            [
                'name' => 'Research Publication Grant',
                'slug' => 'research-publication',
                'description' => 'Support for publishing research in academic journals',
                'requires_vot' => true,
                'field_schema' => [
                    [
                        'name' => 'journal_name',
                        'label' => 'Journal/Publisher Name',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'e.g., IEEE Transactions',
                    ],
                    [
                        'name' => 'paper_title',
                        'label' => 'Paper Title',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Full title of your research paper',
                    ],
                    [
                        'name' => 'publication_type',
                        'label' => 'Publication Type',
                        'type' => 'select',
                        'required' => true,
                        'options' => ['Open Access', 'Subscription', 'Conference Proceedings'],
                    ],
                    [
                        'name' => 'apc_amount',
                        'label' => 'Article Processing Charge (APC)',
                        'type' => 'number',
                        'required' => true,
                        'min' => 0,
                        'step' => 0.01,
                        'help' => 'Enter the total APC amount in RM',
                    ],
                    [
                        'name' => 'acceptance_letter',
                        'label' => 'Acceptance Letter Available',
                        'type' => 'checkbox',
                        'required' => false,
                    ],
                ],
            ],
            [
                'name' => 'Equipment Purchase Request',
                'slug' => 'equipment-purchase',
                'description' => 'Request for purchasing research or lab equipment',
                'requires_vot' => true,
                'field_schema' => [
                    [
                        'name' => 'equipment_name',
                        'label' => 'Equipment Name',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'e.g., Digital Oscilloscope',
                    ],
                    [
                        'name' => 'equipment_model',
                        'label' => 'Model/Specification',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Model number and key specifications',
                    ],
                    [
                        'name' => 'supplier_name',
                        'label' => 'Supplier/Vendor Name',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Company or supplier name',
                    ],
                    [
                        'name' => 'unit_price',
                        'label' => 'Unit Price (RM)',
                        'type' => 'number',
                        'required' => true,
                        'min' => 0,
                        'step' => 0.01,
                    ],
                    [
                        'name' => 'quantity',
                        'label' => 'Quantity',
                        'type' => 'number',
                        'required' => true,
                        'min' => 1,
                    ],
                    [
                        'name' => 'purpose',
                        'label' => 'Purpose and Justification',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 4,
                        'placeholder' => 'Explain why this equipment is needed for your research/teaching',
                    ],
                    [
                        'name' => 'location',
                        'label' => 'Installation Location',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Building/Room where equipment will be installed',
                    ],
                ],
            ],
            [
                'name' => 'Student Activities Fund',
                'slug' => 'student-activities',
                'description' => 'Funding for student club events, competitions, and activities',
                'requires_vot' => true,
                'field_schema' => [
                    [
                        'name' => 'activity_name',
                        'label' => 'Activity/Event Name',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'e.g., Robotic Competition 2024',
                    ],
                    [
                        'name' => 'club_society',
                        'label' => 'Club/Society Name',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Name of organizing club or society',
                    ],
                    [
                        'name' => 'activity_type',
                        'label' => 'Activity Type',
                        'type' => 'select',
                        'required' => true,
                        'options' => ['Competition', 'Workshop', 'Seminar', 'Community Service', 'Social Event'],
                    ],
                    [
                        'name' => 'event_date',
                        'label' => 'Event Date',
                        'type' => 'date',
                        'required' => true,
                    ],
                    [
                        'name' => 'venue',
                        'label' => 'Venue',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Location where event will be held',
                    ],
                    [
                        'name' => 'expected_participants',
                        'label' => 'Expected Number of Participants',
                        'type' => 'number',
                        'required' => true,
                        'min' => 1,
                    ],
                    [
                        'name' => 'activity_description',
                        'label' => 'Activity Description',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 4,
                        'placeholder' => 'Describe the activity, objectives, and expected outcomes',
                    ],
                    [
                        'name' => 'benefits',
                        'label' => 'Benefits to Students/University',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 3,
                        'placeholder' => 'Explain how this activity benefits participants and UniKL',
                    ],
                ],
            ],
            [
                'name' => 'Training & Development Grant',
                'slug' => 'training-development',
                'description' => 'Professional development courses, certifications, and training',
                'requires_vot' => true,
                'field_schema' => [
                    [
                        'name' => 'course_name',
                        'label' => 'Course/Training Name',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'e.g., Certified Data Analyst Program',
                    ],
                    [
                        'name' => 'provider',
                        'label' => 'Training Provider',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Organization offering the training',
                    ],
                    [
                        'name' => 'certification_type',
                        'label' => 'Certification Type',
                        'type' => 'select',
                        'required' => true,
                        'options' => ['Professional Certification', 'Short Course', 'Workshop', 'Conference', 'Seminar'],
                    ],
                    [
                        'name' => 'training_duration',
                        'label' => 'Training Duration',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'e.g., 5 days or 40 hours',
                    ],
                    [
                        'name' => 'training_dates',
                        'label' => 'Training Dates',
                        'type' => 'date_range',
                        'required' => true,
                        'fields' => ['start_date', 'end_date'],
                    ],
                    [
                        'name' => 'relevance',
                        'label' => 'Relevance to Current Role/Studies',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 4,
                        'placeholder' => 'Explain how this training relates to your current position or field of study',
                    ],
                    [
                        'name' => 'knowledge_sharing',
                        'label' => 'Knowledge Sharing Plan',
                        'type' => 'textarea',
                        'required' => false,
                        'rows' => 3,
                        'placeholder' => 'How will you share what you learned with colleagues/students? (optional)',
                    ],
                ],
            ],
            [
                'name' => 'Research Collaboration Fund',
                'slug' => 'research-collaboration',
                'description' => 'Joint research projects with external institutions',
                'requires_vot' => true,
                'field_schema' => [
                    [
                        'name' => 'project_title',
                        'label' => 'Collaborative Project Title',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Full title of the joint research project',
                    ],
                    [
                        'name' => 'partner_institution',
                        'label' => 'Partner Institution',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'University, company, or research institute',
                    ],
                    [
                        'name' => 'partner_country',
                        'label' => 'Partner Country',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'e.g., Japan, Germany, Singapore',
                    ],
                    [
                        'name' => 'collaboration_type',
                        'label' => 'Type of Collaboration',
                        'type' => 'select',
                        'required' => true,
                        'options' => ['Joint Research', 'Student Exchange', 'Staff Exchange', 'Industry Partnership', 'MOU Activity'],
                    ],
                    [
                        'name' => 'uniKL_role',
                        'label' => 'UniKL Role in Collaboration',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 3,
                        'placeholder' => 'Describe UniKL\'s contribution and responsibilities',
                    ],
                    [
                        'name' => 'project_duration',
                        'label' => 'Project Duration',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'e.g., 12 months or 2 semesters',
                    ],
                    [
                        'name' => 'expected_outcomes',
                        'label' => 'Expected Outcomes/Deliverables',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 4,
                        'placeholder' => 'List expected publications, patents, products, or other outputs',
                    ],
                    [
                        'name' => 'funding_source',
                        'label' => 'Other Funding Sources (if any)',
                        'type' => 'text',
                        'required' => false,
                        'placeholder' => 'e.g., External grants, industry sponsorship',
                    ],
                ],
            ],
            [
                'name' => 'Innovation & Entrepreneurship Grant',
                'slug' => 'innovation-entrepreneurship',
                'description' => 'Support for student startups and innovation projects',
                'requires_vot' => true,
                'field_schema' => [
                    [
                        'name' => 'project_name',
                        'label' => 'Project/Startup Name',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Name of your innovation or startup',
                    ],
                    [
                        'name' => 'team_members',
                        'label' => 'Team Members',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 3,
                        'placeholder' => 'List all team members with their roles and student IDs',
                    ],
                    [
                        'name' => 'project_category',
                        'label' => 'Project Category',
                        'type' => 'select',
                        'required' => true,
                        'options' => ['Technology/Innovation', 'Social Enterprise', 'Creative/Media', 'Service Business', 'Product Development'],
                    ],
                    [
                        'name' => 'problem_statement',
                        'label' => 'Problem Statement',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 4,
                        'placeholder' => 'What problem does your project solve?',
                    ],
                    [
                        'name' => 'solution_description',
                        'label' => 'Proposed Solution',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 4,
                        'placeholder' => 'Describe your solution and how it addresses the problem',
                    ],
                    [
                        'name' => 'target_market',
                        'label' => 'Target Market/Customers',
                        'type' => 'text',
                        'required' => true,
                        'placeholder' => 'Who will use or buy your product/service?',
                    ],
                    [
                        'name' => 'development_stage',
                        'label' => 'Current Development Stage',
                        'type' => 'select',
                        'required' => true,
                        'options' => ['Idea/Concept', 'Prototype', 'Minimum Viable Product', 'Early Sales', 'Growth Stage'],
                    ],
                    [
                        'name' => 'milestones',
                        'label' => 'Key Milestones & Timeline',
                        'type' => 'textarea',
                        'required' => true,
                        'rows' => 4,
                        'placeholder' => 'List major milestones and when you plan to achieve them',
                    ],
                    [
                        'name' => 'mentor_advisor',
                        'label' => 'Mentor/Advisor (if any)',
                        'type' => 'text',
                        'required' => false,
                        'placeholder' => 'Name of academic or industry mentor',
                    ],
                ],
            ],
        ];

        foreach ($types as $type) {
            RequestType::updateOrCreate(
                ['slug' => $type['slug']],
                $type
            );
        }
    }
}
